In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(3,8)

array([8, 8, 8])

In [6]:
a = np.array([1,2,3,5,7,12])

In [7]:
a[3]

np.int64(5)

In [8]:
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2] = 10

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])


In [14]:
n[0,1]=20

In [15]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
n[2]

array([7, 8, 9])

In [17]:
n[2]=[1,1,1]

In [18]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:,2] = [1,2,1]

In [20]:
n

array([[ 1, 20,  1],
       [ 4,  5,  2],
       [ 1,  1,  1]])

In [21]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a + 1

array([1, 2, 3, 4, 5])

In [25]:
b = np.random.randint(0,6,(1,5))[0]
print(b)
ab = np.where(a>b,True,0)
ab

[3 1 2 0 4]


array([0, 0, 0, 1, 0])

a = np.arange(5)
for i in a:
    print(i)

In [26]:
a.max()

np.int64(4)

In [55]:
U = np.random.randint(0,10,(4,3))
V = np.random.randint(0,10,(3,5))

In [28]:
print(U)
print(V)

[[2 4 1]
 [7 8 2]
 [9 8 7]
 [1 6 8]]
[[5 9 9 9]
 [3 0 0 2]
 [8 8 2 9]]


In [56]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    result = np.zeros((U.shape[0],V.shape[1]))
    for a in range(U.shape[0]):
        for b in range(V.shape[1]):
            for i in range(U.shape[1]):
                #print(U[a],V[:,b])
                result[a,b] = result[a,b] + U[a][i]*V[:,b][i]
    return result            
            

m = matrix_matrix_multiplication(U,V)
m


array([[104., 107.,  60.,  26.,  67.],
       [ 84., 105.,  66.,  30.,  57.],
       [ 64.,  89.,  52.,  16.,  31.],
       [ 64.,  95.,  68.,  36.,  53.]])

In [57]:
U.dot(V)

array([[104, 107,  60,  26,  67],
       [ 84, 105,  66,  30,  57],
       [ 64,  89,  52,  16,  31],
       [ 64,  95,  68,  36,  53]])

In [43]:
V.dot(U)

array([[163, 218, 158],
       [  8,  24,  19],
       [ 99, 166, 110]])